### ISSUE TITLE
NMState required NetworkManager start from 1.2 version only ?

### ISSUE THREAD

**Issue by wdrdres3qew5ts21** [nmstate/kubernetes-nmstate#1054]
**What happened**:
I had notice that in developer guide document said it required NetworkManager start from 1.2 version so it mean if I'm using Openshift that Worker Node using Network Manager 1.8 version my NMState operator will never working right ?
Here is my server detail
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

sh-4.2# nmcli -v
nmcli tool, version 1.18.8-2.el7_9
```
Because currently I had problem that my NNCP never display status as success or failure even though I already install NetworkManagerAddons already and Operator seem working fine.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/25000903/163721757-6d6e5d11-19b9-4169-955f-df9099e23174.png">
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/25000903/163721800-f1632cc6-5886-4c05-bf59-65ca1856b65c.png">
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/25000903/163721814-f0094577-954f-4389-9eb9-d8851352d869.png">

Here is my CR file

**What you expected to happen**:
NNCP should display status or can create Linux Bridge to Kubernetes Node

**Environment**:

- Problematic `NodeNetworkConfigurationPolicy`:
```yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: brse-eth1
spec:

  desiredState:
    interfaces:
    - name: brse
      description: Linux bridge with eth1 as a port
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: eth1
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: eth666
spec:
  desiredState:
    interfaces:
    - name: eth666
      type: ethernet
      state: up

```
- NetworkManager version (use `nmcli --version`)
```
sh-4.2# nmcli -v
nmcli tool, version 1.18.8-2.el7_9
```
- Kubernetes version (use `kubectl version`):
Openshift 4.8
