### ISSUE TITLE
NNCP status not updated after cluster scale down

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#1098]
**What happened**:
When a node from a cluster is removed the NNCP status is still showing the same number of nodes

```yaml
  status:
    conditions:
    - lastHeartbeatTime: "2022-06-08T13:35:03Z"
      lastTransitionTime: "2022-06-08T13:35:03Z"
      message: 2/2 nodes successfully configured
      reason: SuccessfullyConfigured
      status: "True"
      type: Available
```

**What you expected to happen**:

NNCP status has to be updated with current number of nodes

```yaml
  status:
    conditions:
    - lastHeartbeatTime: "2022-06-08T13:35:03Z"
      lastTransitionTime: "2022-06-08T13:35:03Z"
      message: 1/1 nodes successfully configured
      reason: SuccessfullyConfigured
      status: "True"
      type: Available
```

**How to reproduce it (as minimally and precisely as possible)**:
- Apply an NNCP
- Remove a node from the cluster
- 
**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:
