### ISSUE TITLE
dns probe failed, need to disable dns check

### ISSUE THREAD

**Issue by k8scoder192** [nmstate/kubernetes-nmstate#1164]
**What happened**:
When applying 
```
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vpc-mgmt-v100
spec:
  nodeSelector:
    networkmanager: "true"
    kubernetes.io/hostname: vmaas-worker2
  desiredState:
    interfaces:
    - name: "vpc-mgmt-v100"
      type: vlan
      state: up
      mac-address: 02:b0:ad:33:bb:98
      vlan:
        id: 100
        base-iface: bond0
      ipv4:
        dhcp: false
        enabled: false
```
**nncp** sits for a while with no status and **nnce** says ConfigurationProgressing

When I look at the **nmstate-handler** pod I see it fails for DNS check 
```
{"level":"error","ts":"2023-04-03T19:34:49.252Z","logger":"probe","msg":"failed checking DNS connectivity","error":"[lookup root-server.net on <redacted_ip>:53: no such host lookup root-server.net on<redacted_ip>:53: no such host lookup root-server.net on <redacted_ip>:53:  ....
```

Also what is **root-server.net** ?? It's also hardcoded in kubernetes-nmstate/pkg/probe/probes.go

**What you expected to happen**:
nmstate to not check dns probe if we don't want it to (or let me know how to get around this problem).

**How to reproduce it (as minimally and precisely as possible)**:
See above 

**Anything else we need to know?**:

**Environment**:
quay.io/nmstate/kubernetes-nmstate-handler:v0.74.0

quay.io/nmstate/kubernetes-nmstate-handler:v0.74.0

quay.io/nmstate/kubernetes-nmstate-operator:v0.74.0

quay.io/nmstate/kubernetes-nmstate-handler:v0.74.0

quay.io/nmstate/kubernetes-nmstate-handler:v0.74.0

Ubuntu 18.04 OS  / kernel 4.15.xx

nmcli tool, version 1.40.6

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:
