### ISSUE TITLE
ovs-bridge plugin unavailable

### ISSUE THREAD

**Issue by sudharsanomprakash** [nmstate/kubernetes-nmstate#1182]
**What happened**:
Trying to add ovs bridge and getting below error
"NmstateError: DependencyError: Manager(MissingPlugin):NetworkManager plugin for 'ovs-bridge' unavailable"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`: 
```
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-test
spec:
  desiredState:
    interfaces:
    - name: br10
      description: ovs bridge with ens50 as a port
      type: ovs-bridge
      state: up
      bridge:
        options:
          stp: false
        port:
        - name: ens50
```
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`): quay.io/nmstate/kubernetes-nmstate-handler:v0.77.0
- NetworkManager version (use `nmcli --version`) nmcli tool, version 1.22.10
- Kubernetes version (use `kubectl version`): v1.24.2
- OS (e.g. from /etc/os-release): Node's are ubuntu 20.04
- Others:
