### ISSUE TITLE
[RFE] Collect nmstate usage  data for telemetry

### ISSUE THREAD

**Issue by cathay4t** [nmstate/kubernetes-nmstate#1202]
We are hoping to get data on 
 * What is the commonly used network topology? (e.g. VLAN over  linux bridge over bond)
 * Version of nmstate been used

This could help us on planning CI coverage and backport patches.

**Comment by cathay4t** [comment]
Initially, I would like to collect date for:
 1. Topology: array of free strings, like `vlan`, `linux-bridge`, `vlan-over-bridge-over-bond`, `ovs-bridge` etc.
 2. Features, array of free strings, like `mac-based-identifier`, `ovn-mapping`. With this we could know adoption rate of  implemented features.
 3. Use cases. array of free strings. like `move ip from eth to bridge`, `change dns nameservers`, `switch from dynamic ip to static`. We can use nmstate tier1 test case name for naming these use cases, so we have clear definition.
 4. Optionally, learn use case of customer's desire state. Till suggested this, but I don't know how to do it.

Each cluster only count as one for topology/feature/use case regardless how many interfaces it has or how many NNCP it has. So our data does not imfluenced by a big cluster with 1000+ VLANs or NNCPs.

I will create demo like `nmstatectl gen-statistics <desire_state_file> [-c <current_state_file>]`:

```yml
topologies:
  - vlan
  - linux-bridge-over-bond-over-sriov-vf
features:
 - nm-global-dns
 - mac-identifier
 - sriov-vf-reference
 - ovn-mapping
use-cases:
 - edit_static_ipv4_address_and_prefix
 - disable_static_ipv6
```
