### ISSUE TITLE
Cannot configure route when ipv4.enabled == false

### ISSUE THREAD

**Issue by fbecker** [nmstate/kubernetes-nmstate#1231]
**What happened**:
Static route configuration fails when configuring next-hop-interface to an interface where ip is disabled.

I'm getting the following error from nnce:

> NmstateError: InvalidArgument: The next hop interface of desired Route 'destination: 192.168.150.0/24 next-hop-interface: ens224' has been marked as IPv4 disabled

**What you expected to happen**:
To be able to add a route without a next-hop-interface or configured IP address. Just like
```
ip route add 192.168.150.0/24 dev ens224
```

**How to reproduce it (as minimally and precisely as possible)**:
``` yaml
spec:
  desiredState:
    interfaces:
    - name: ens224
      state: up
      type: ethernet
    routes:
      config:
      - destination: 192.168.150.0/24
        next-hop-interface: ens224
```

**Comment by qinqon** [comment]
@cathay4t do you know if we have an issue at nmstate for this ?

**Comment by cathay4t** [comment]
As the message indicate, you cannot have route on disabled IP stack.

You have to enable IP stack even without address mentioned.

```
---
routes:
  config:
  - destination: 198.51.100.0/24
    metric: 150
    next-hop-interface: eth1
    table-id: 254
interfaces:
  - name: eth1
    type: ethernet
    state: up
    ipv4:
      enabled: true
```

**Comment by cathay4t** [comment]
On second thought, nmstate should support YAML provided by @fbecker , let generate a patch for it.

https://github.com/nmstate/kubernetes-nmstate/issues/1231#issuecomment-2121944023 could be used as workaround.

**Comment by cathay4t** [comment]
I have PR https://github.com/nmstate/nmstate/pull/2677 created to support:

```yml
---
routes:
  config:
  - destination: 198.51.100.0/24
    metric: 150
    next-hop-interface: eth1
    table-id: 254
interfaces:
  - name: eth1
    type: ethernet
    state: up
    ipv4:
      enabled: true
      address: []
```

But routes on disabled IP is still invalid use case.
