### ISSUE TITLE
add OPTIONS to routes.config 

### ISSUE THREAD

**Issue by gsustek** [nmstate/kubernetes-nmstate#1262]
Is it possible to set OPTIONS from [iproute](https://man7.org/linux/man-pages/man8/ip-route.8.html) command like QUICKACK to all routes in the pod ?

```
---
interfaces:
  - name: eth1
    type: ethernet
    state: up
    ipv4:
      address:
        - ip: 192.0.2.251
          prefix-length: 24
      dhcp: false
      enabled: true
routes:
  config:
    - destination: 198.51.100.0/24
      metric: 150
      next-hop-address: 192.0.2.1
      next-hop-interface: eth1
      table-id: 254
      options:
        - quickack 1
```
         
         
         update:
         it seems that quickack is supported as ipv4 and ipv6 routes arguments:
         https://networkmanager.dev/docs/api/latest/nm-settings-nmcli.html

    Regards,
Goran
