### ISSUE TITLE
Unable to change to a static IP address on a single-node k3s cluster.

### ISSUE THREAD

**Issue by liushan9981** [nmstate/kubernetes-nmstate#1274]
**What happened**:
Created an NNCP resource to configure a static IP address, routing, and DNS. After a while, the NNCP status shows as Degraded.
Error message after running "kubectl describe nncp ip1":
```
Warning  ReconcileFailed  10m   <myhostname>.nmstate-handler  error reconciling NodeNetworkConfigurationPolicy on node <myhostname> at desired state apply: "",
 rolling back desired state configuration: failed runnig probes after network changes: failed runnig probe 'api-server' with after network reconfiguration -> currentState: hostname:
```

**What you expected to happen**:
Changing to a static IP should be successful, including the k3s services, and all pods should function normally.

**How to reproduce it (as minimally and precisely as possible)**:
- Install k3s on a single machine as a single-node k3s cluster
- Using the manifest to create a nncp
- Watch the status of the nncp we created above.

nncp manifest:
```
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ip1
spec:
  nodeSelector:
    kubernetes.io/hostname: k3s-server
  desiredState:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: 10.1.1.55
          prefix-length: 24
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.1.1.1
          next-hop-interface: eth0
          metric: 100
          source: 10.1.1.55
    dns-resolver:
      config:
        search:
        - .
        server:
        - 8.8.4.4
```

**Anything else we need to know?**:

**Environment**:

- nmstate-operator version: v0.83.0
- OS: SUSE micro SLE 5.5
- k3s version: v1.31.1+k3s1
