### ISSUE TITLE
Support vlan-filtering configuration

### ISSUE THREAD

**Issue by qinqon** [nmstate/kubernetes-nmstate#171]
Starting with version 0.3, nmstate allows users to configure [vlan-filtering options](https://github.com/nmstate/nmstate/pull/892), e.g.:

```yaml
interfaces:
  - name: linux-br0
    type: linux-bridge
    state: up
    bridge:
      port:
        - name: eth1
          vlan:
            mode: trunk
            trunk-tags:
            - id: 101
            - id-range:
                min: 500
                max: 599
            tag: 100
            enable-native: true
```

kubernetes-nmstate however handles the vlan-filtering configuration with a [workaround script](https://github.com/nmstate/kubernetes-nmstate/blob/master/build/bin/vlan-filtering) which makes sure to enable vlan-filtering by default and treat all bridge ports as trunks.

In order to introduce support for this feature while maintaining backwards compatibility, we should:

* Drop the custom script.
* In case no VLAN configuration is passed by the user, we should fill in defaults matching the behaviour of the script.

### Original description

Until we don't use NetworkManager to set vlan filtering (with or without nmstate) the linux bridge vlan_filtering flag is only set after desiredState is processed, so after reboot the flag is not going to be there until kubernetes-nmstate is not up and NodeNetworkState processed.
