### ISSUE TITLE
Failed to create BOND.

### ISSUE THREAD

**Issue by myakove** [nmstate/kubernetes-nmstate#278]
Using:
```yaml
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond1nncp
spec:
  desiredState:
    interfaces:
    - link-aggregation:
        mode: active-backup
        options:
          miimon: "120"
        slaves:
        - ens7
        - ens8
      name: bond1
      state: up
      type: bond
```

https://paste.fedoraproject.org/paste/ODZv3UlZwK8WPnTw4vI8~Q
