### ISSUE TITLE
Setup fails if there is no default route

### ISSUE THREAD

**Issue by phoracek** [nmstate/kubernetes-nmstate#316]
**What happened**:
When there is no default route on the host, we refuse to apply any configuration. It is blocked due to the fact that we use the default gw to perform connectivity check. 

```
econciling NodeNetworkConfigurationPolicy at desired state apply: , rollback cause: Impossible to retrieve default gw, state: ---
dns-resolver:
  config:
    search: []
    server: []
  running: {}
route-rules:
  config: []
routes:
  config: []
  running:
  - destination: 10.244.0.0/24
    metric: 0
    next-hop-address: ''
    next-hop-interface: cni0
    table-id: 254
  - destination: 172.17.0.0/16
    metric: 0
    next-hop-address: ''
    next-hop-interface: docker0
    table-id: 254
  - destination: fe80::/64
    metric: 256
    next-hop-address: ''
    next-hop-interface: cni0
    table-id: 254
  - destination: ff00::/8
    metric: 256
    next-hop-address: ''
    next-hop-interface: cni0
    table-id: 255
```

**What you expected to happen**:
There should be a fallback plan. We should either pick other target to ping or just skip the check.

**How to reproduce it (as minimally and precisely as possible)**:
Remove default route and try to apply any config.
