### ISSUE TITLE
Node's nmstate status is different from the actual status of the node

### ISSUE THREAD

**Issue by mardim91** [nmstate/kubernetes-nmstate#399]
**What happened**:

I am running the `kubectl get nns <node-name> -o yaml` to get the node's status. The output of the status is different from the actual status of the node 

**What you expected to happen**:

So to give an example of the above problem. 

- nmstate node's status output:
```yaml
      ipv4:
        enabled: false
      ipv6:
        enabled: false
      mac-address: 52:54:00:73:58:32
      mtu: 1500
      name: ens3
      state: down
      type: ethernet
```

- ip a command output: 

  ` ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:73:58:32 brd ff:ff:ff:ff:ff:ff
` 

The ens3 interface is clearly up.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy kubernetes in Ubuntu (bionic-beaver) with kubeadm. Follow the instructions for the deploy of kubernetes-nmstate for the arbitrary cluster. 

- Run `kubectl get nns <node-name> -o yaml`
- Run `ip a`
- Compare the outputs
