### ISSUE TITLE
Unable to create DNS configuration

### ISSUE THREAD

**Issue by mardim91** [nmstate/kubernetes-nmstate#416]
**What happened**:

Tried to create some dns configuration throught this yaml:  https://hastebin.com/rajibelivu.makefile

But I got this error: https://hastebin.com/ujalozusip.sql

**Comment by phoracek** [comment]
Policy:

```yaml
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dns
spec:
  desiredState:
     dns-resolver:
        config:
          search:
          - example.com
          - example.org
          server:
          - 8.8.8.8 
```

Error:

```yaml
essage: |-
      error reconciling NodeNetworkConfigurationPolicy at desired state apply: , failed to execute nmstatectl set --no-commit --timeout 240: 'exit status 1' '' 'Traceback (most recent call last):
        File "/usr/bin/nmstatectl", line 11, in <module>
          load_entry_point('nmstate==0.2.1', 'console_scripts', 'nmstatectl')()
        File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 59, in main
          return args.func(args)
        File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 221, in apply
          return apply_state(statedata, args.verify, args.commit, args.timeout)
        File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 237, in apply_state
          checkpoint = libnmstate.apply(state, verify_change, commit, timeout)
        File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 60, in apply
          validator.validate_capabilities(desired_state, netinfo.capabilities())
        File "/usr/lib/python3.7/site-packages/libnmstate/validator.py", line 60, in validate_capabilities
          validate_interface_capabilities(state[Constants.INTERFACES], capabilities)
      KeyError: 'interfaces'
      '
    reason: FailedToConfigure
    status: "True"
    type: Failing
  - lastHearbeatTime: "2020-02-13T16:05:06Z"
    lastTransitionTime: "2020-02-13T16:05:06Z"
    reason: FailedToConfigure
    status: "False"
    type: Available
  - lastHearbeatTime: "2020-02-13T16:05:06Z"
    lastTransitionTime: "2020-02-13T16:05:06Z"
    reason: FailedToConfigure
    status: "False"
    type: Progressing
  - lastHearbeatTime: "2020-02-13T16:04:49Z"
    lastTransitionTime: "2020-02-13T16:04:49Z"
    message: All policy selectors are matching the node
    reason: AllSelectorsMatching
    status: "True"
    type: Matching
  desiredState:
    dns-resolver:
      config:
        search:
        - example.com
        - example.org
        server:
        - 8.8.8.8
```
