### ISSUE TITLE
Job publish-kubernetes-nmstate of type postsubmit ended with state failure.

### ISSUE THREAD

**Issue by dhiller** [nmstate/kubernetes-nmstate#628]
**What happened**:
 Job [publish-kubernetes-nmstate](https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml#L3) failed: 
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubernetes-nmstate/1326166839411085312
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubernetes-nmstate/1326216416252137472
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubernetes-nmstate/1326259825721479168

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

/kind bug
/triage build-watcher

**Comment by qinqon** [comment]
The publish job has to ignore `gh-pages` this is a special branch to dump jekyll output and have a documentation as a github page.

```yaml
 refs:
    base_link: https://github.com/nmstate/kubernetes-nmstate/compare/c8f9fc3de6d2...3b0922100c37
    base_ref: gh-pages
    base_sha: 3b0922100c373f27af0615f09e0db9cf2332d27a
    org: nmstate
    repo: kubernetes-nmstate
```
