### ISSUE TITLE
Missing nnce where running create delete flow

### ISSUE THREAD

**Issue by oshoval** [nmstate/kubernetes-nmstate#782]
Create 2 bridges (each for different secondary interface) using 2 nncps
wait for it to finish according nnce
delete the nncp
create 2 nncps that "absent" the bridges

**What happened**:
Wait for the bridges to be gone
watch all the way the nnce and see that just the 2nd one appear, the first one
isn't created even after the bridge actually gone from the node.
(the 2nd one appears in delay because k8s-nmstate actually do process the first one as a ghost)

final state
```
$ oc get nnce
NAME         STATUS
node01.br2   Available
```
```
$ oc get nncp
NAME   STATUS
br1    
br2    Available
```

**What you expected to happen**:
all nnce should appear

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
used CNAO vanilla with 2 secondary interfaces

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by rhrazdil** [comment]
Hey @oshoval, could you provide manifests for the bridges?
When using
```
---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1
spec:
  nodeSelector:
    kubernetes.io/hostname: node02
  desiredState:
    interfaces:
    - name: br100
      type: linux-bridge
      state: down
---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br2
spec:
  nodeSelector:
    kubernetes.io/hostname: node02
  desiredState:
    interfaces:
    - name: br200
      type: linux-bridge
      state: down
```
and subsequently
```
---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-absent
spec:
  nodeSelector:
    kubernetes.io/hostname: node02
  desiredState:
    interfaces:
    - name: br100
      type: linux-bridge
      state: absent
---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br2-absent
spec:
  nodeSelector:
    kubernetes.io/hostname: node02
  desiredState:
    interfaces:
    - name: br200
      type: linux-bridge
      state: absent
```

All NNCEs are Available
```
NAME                        STATUS
node02.br1                  Available
node02.br1-absent           Available
node02.br2                  Available
node02.br2-absent           Available

```

**Comment by oshoval** [comment]
and br2 / eth2 for the 2nd of course
```
cat <<EOL | kubectl create -f -
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1
spec:
  desiredState:
    interfaces:
    - name: br1
      description: Linux bridge
      type: linux-bridge
      state: up
      bridge:
        port:
        - name: eth1
EOL
```
