### ISSUE TITLE
NNCPs that break node connectivity cause reconcile to fail update status

### ISSUE THREAD

**Issue by rhrazdil** [nmstate/kubernetes-nmstate#785]
**What happened**:
NNCE is in Failing state, but status of NNCP has not been updated.

**What you expected to happen**:
Policy should end up in Degraded state

**How to reproduce it (as minimally and precisely as possible)**:
Create a NNCP that breaks network connectivity by setting wrong IP address to eth0 
```
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: mark-bridge-remove
spec:
  nodeSelector:
    kubernetes.io/hostname: node02
  desiredState:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: "192.168.45.33" 
          prefix-length: 24
        dhcp: false
        enabled: true
```
**Anything else we need to know?**:
The reason for this is apparently that it takes some time for the watchers to reconnect.
Until that happens, `err := cli.Get(context.TODO(), policyKey, policy)` returns cached policy resource with
outdated `resourceVersion`, and 
https://github.com/nmstate/kubernetes-nmstate/blob/2717b01fd04abf951b149a0868f3908888fc6ff6/pkg/policyconditions/conditions.go#L90
fails to update status in all retries.

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:
